POST https://bootcamp-apis-5lik.onrender.com/api/enough
content-type: application/json

{
    "Usage" : "call,sms,call",
    "availableAirtime" : 54
}

###
 POST https://bootcamp-apis-5lik.onrender.com/api/phonebill/total
content-type: application/json

{
    "bill" : "call,sms,call"
}

###
GET https://bootcamp-apis-5lik.onrender.com/api/phonebill/prices
content-type: application/json

{
    "call" : 2.75,
    "sms" : 0.65
}


###
POST https://bootcamp-apis-5lik.onrender.com/api/phonebill/price
content-type: application/json

{
    "type" : "sms",
    "price" : 2.85
}
